'on': 
  pull_request:
    paths:
      - img-region-select-app/**
      - .github/workflows/contentful-image-merge.yml
      - .github/workflows/contentful-image-release.yml
      - .github/workflows/image-pull-request.yml
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          cd img-region-select-app
          npm ci
      - name: Build
        run: |
          cd img-region-select-app
          npm run build