'on': 
  pull_request:
    paths:
      - qr-code-app/**
      - .github/contentful-qr-code-merge.yml
      - .github/contentful-qr-code-release.yml
      - .github/qr-code-pull-request.yml
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          cd qr-code-app
          npm ci
      - name: Build
        run: |
          cd qr-code-app
          npm run build